title: Conceptionalis-Philosophica Contemplatio
description: An attempt to construct a cohesive conceptual-philosophical framework from the ground up.
author:
        name: "Christopher Dumas"
        email: "christopherdumas@gmail.com"
